version: "3.2"
services:
  app:
    image: 4soatg44/ms-fb-cadastro:1.0.0
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/challenge"
      SPRING_DATASOURCE_USERNAME: "arch"
      SPRING_DATASOURCE_PASSWORD: "challenge"
      SPRING_PORT: "8080"
      MERCADO_TOKEN: "Bearer TEST-8984958385382549-010720-8b45e680cd085f9976863a95655daff7-143716477"
      TOKEN_FALLBACK: "ODk4NDk1ODM4NTM4MjU0OS0wMTA3MjAtOGI0NWU2ODBjZDA4NWY5OTc2ODYzYTk1NjU1ZGFmZjctMTQzNzE2NDc3"
      AWS_ACCESS_KEY_ID: ""
      AWS_SECRET_ACCESS_KEY: ""
      AWS_COGNITO_USER_POOL_ID: "us-east-1_ssXveW6jC"
      MERCADO_API: "https://api.mercadopago.com"
      SPRING_DATA_MONGODB_HOST: "44.212.233.147"
      SPRING_DATA_MONGODB_PORT: "27017"
      SPRING_DATA_MONGODB_DATABASE: "fastburger"
      SPRING_DATA_MONGODB_USERNAME: "deckbuilder"
      SPRING_DATA_MONGODB_PASSWORD: "gzeqPuVU6uju7nLxibTt"
      SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: "admin"
    networks:
      - netChallenge
    restart: always
volumes:
  volume-db-challenge:
  valume-api-challenge:

networks:
  netChallenge:
    driver: bridge
